name: pg-idris tests
on: 
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: mattpolzin2/idris-docker:nightly

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      IDRIS2_CG: chez
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

    steps:
      - name: Install Dependencies
        run: apt-get -y install git libpq-dev libpq5 libc6-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build pg-idris
        run: make && make install
      - name: Test pg-idris
        run: |
          echo "LD_LIBRARY_PATH=$(idris2 --libdir)/pg-idris/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV && \
          make test INTERACTIVE=''

